# -*- coding: utf-8 -*-
"""BE175_FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8kAAjt1h80DpURrq1gpLxe6QoVslkkR
"""

import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import LeaveOneGroupOut, cross_val_predict
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

# read datasets
logfold_raw= pd.read_csv('/content/primary-screen-replicate-collapsed-logfold-change.csv', index_col=0)
drug_metadata= pd.read_csv('/content/biomarkers.csv')

# drop cell lines with missing data NaN
logfold_v2 = logfold_raw.dropna(axis=0).dropna(axis=1)

print(f"Original shape: {logfold_raw.shape}")
print(f"Shape after dropping drug and cell lines with NaNs: {logfold_v2.shape}")

# cleaning drug dataset - clean missing identifiers and strip whitespace from matching columns
drug_metadata = drug_metadata.dropna(subset=['column_name'])
drug_metadata['column_name'] = drug_metadata['column_name'].str.strip()
logfold_v2.columns = logfold_v2.columns.str.strip()

# Extract the alignment keys that exist simultaneously in both datasets
valid_drug_keys = logfold_v2.columns.intersection(drug_metadata['column_name'])

# Filter target matrix to only retain matched compounds
logfold_v3 = logfold_v2[valid_drug_keys]
Y_matrix = logfold_v3.T # to make drug rows (to match biomarker data)

# Set the index of your drug metadata to match the filtered layout
drug_metadata_filtered = drug_metadata[drug_metadata['column_name'].isin(valid_drug_keys)].set_index('column_name')

print(f"Shape of filtered metadata: {drug_metadata_filtered.shape}")

# Fill missing targets with a placeholder string before encoding
drug_metadata_filtered['target'] = drug_metadata_filtered['target'].fillna('Unknown_Target')

# One-hot encode the target proteins
X_features = pd.get_dummies(drug_metadata_filtered['target'], prefix='target')

# Group by the index (column_name) just in case a drug maps to multiple targets
X_features = X_features.groupby(X_features.index).sum()

# Reindex both matrices to ensure identical row order
common_indices = X_features.index.intersection(Y_matrix.index)
X_final = X_features.loc[common_indices]
Y_final = Y_matrix.loc[common_indices]

# Create masks using the drug_category column from your filtered metadata
is_cancer = drug_metadata_filtered.loc[common_indices, 'drug_category'] == 'targeted cancer'
is_noncancer = drug_metadata_filtered.loc[common_indices, 'drug_category'] == 'noncancer'

# Training Set (Targeted Cancer Drugs)
X_train = X_final[is_cancer].values
Y_train = Y_final[is_cancer].values

# Testing Set (Noncancer Drugs)
X_test = X_final[is_noncancer].values
Y_test = Y_final[is_noncancer].values

print(f"Training set size (Cancer drugs): {X_train.shape[0]}")
print(f"Testing set size (Noncancer drugs): {X_test.shape[0]}")

# PCA
scaler= StandardScaler() # standardization step
Xscaled= scaler.fit_transform(Y_matrix)

pca= PCA(n_components= 10)
X_pca= pca.fit_transform(Xscaled)

# variance explained by each component
explained_variance= pca.explained_variance_ratio_
print(f"Explained variance ratio of first 3 PCs: {explained_variance[:3]}")

# for PCA plot
pca_df = pd.DataFrame(X_pca[:, :2], columns=['PC1', 'PC2'])
Y_matrix.index = Y_matrix.index.str.strip()
drug_metadata['column_name'] = drug_metadata['column_name'].astype(str).str.strip()

# Map drug codes to categories
cat_map = drug_metadata.set_index('column_name')['drug_category'].to_dict()
pca_df['Category'] = [cat_map.get(col, 'Unknown') for col in Y_matrix.index]

# 7. Generate Scatter Plot
plt.clf()
colors = {'targeted cancer': '#E23C4A', # Red
        'noncancer': '#748CAA',       # Blue
        'chemo': '#2ca02c',           # Green
         }

for cat, group in pca_df.groupby('Category'):
  plt.scatter(group['PC1'], group['PC2'], label=cat, color=colors.get(cat, '#7f7f7f'),
            alpha=0.6, s=15)

plt.xlabel(f'PC1 ({explained_variance[0]*100:.1f}%)')
plt.ylabel(f'PC2 ({explained_variance[1]*100:.1f}%)')
plt.title('PCA of Drug Response Profiles Across Cancer Cell Lines')
plt.legend(title="Drug Category")
plt.show()

# PLSR
# cross validation to determine the optimal number of components
n_samples=X_train.shape[0]
test_comps=range(1,15) # arbitrary range of number of components to test
cv_mse_scores=[]
Q2Ys=[]

for n_comp in test_comps:
    plsr_comp= PLSRegression(n_components= n_comp)
    Y_cv_pred= cross_val_predict(plsr_comp, X_train, Y_train, cv=10) # 10-fold
    mse= mean_squared_error(Y_train, Y_cv_pred)
    cv_mse_scores.append(mse)
    tss= np.sum((Y_train - np.mean(Y_train)) ** 2)
    press=np.sum((Y_train - Y_cv_pred) ** 2)
    Q2Y=1-(press/tss)
    Q2Ys.append(Q2Y)

# plotting Q2Y vs. num of components
plt.plot(test_comps, Q2Ys, marker='o')
plt.xlabel('Number of Components')
plt.ylabel('$Q^2$Y')
plt.title('Q2Y vs Number of Components')
plt.show()

# obtaining optimal number of components based on MSE and Q2Y
if np.argmin(cv_mse_scores) == np.argmax(Q2Ys):
    best_n_comp= test_comps[np.argmax(Q2Ys)]
    print(f'Optimal number of components: {best_n_comp}')
elif np.argmin(cv_mse_scores) > np.argmax(cv_mse_scores):
    print('minimum of CV error greater than maximum of Q2Y')
else:
    print('minimum of CV error less than maximum of Q2Y')

# PLSR
plsr = PLSRegression(n_components=best_n_comp)

# fitting with training dataset
plsr.fit(X_train, Y_train)

# Predict viability across all cell lines for the withheld noncancer drugs
Y_pred = plsr.predict(X_test)

# Calculate performance metrics
r2 = r2_score(Y_test, Y_pred, multioutput='variance_weighted')
r2y= plsr.score(X_test, Y_test)
mse = mean_squared_error(Y_test, Y_pred)

print(f"Variance Weighted R^2 Score: {r2:.4f}")
print(f"R2Y Score: {r2y:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")

# Calculate the average predicted killing effect (lower/more negative LFC is better)
mean_predicted_lfc = Y_pred.mean(axis=1)

# Get the actual names of the noncancer test drugs
noncancer_drug_names = drug_metadata_filtered.loc[common_indices][is_noncancer]['name'].values

# Targets of the drugs
targets = drug_metadata_filtered.loc[common_indices][is_noncancer]['target'].values

results_df = pd.DataFrame({
    'Drug_Name': noncancer_drug_names,
    'Avg_Predicted_LFC': mean_predicted_lfc,
    'Target': targets
}).sort_values(by='Avg_Predicted_LFC')

print("\nTop 10 noncancer drugs predicted to have the strongest anti-cancer profiles:")
print(results_df.head(10))

print("\nTop 10 noncancer drugs predicted to have the weakest anti-cancer profiles:")
print(results_df.tail(10))

strongdrug_counter= 0
for i in range(0, len(mean_predicted_lfc)):
  if mean_predicted_lfc[i]<= -1:
    strongdrug_counter= strongdrug_counter+1
  else:
    strongdrug_counter= strongdrug_counter

anticancer_drugs= results_df.head(strongdrug_counter)["Drug_Name"].values
anticancer_ind= results_df.head(strongdrug_counter).index
anticancer_targets= results_df.head(strongdrug_counter)["Target"].values

X_test_scores= plsr.transform(X_test)

X_scores_bg= X_test_scores[~anticancer_ind]
X_scores_anticancer= X_test_scores[anticancer_ind]

X_loadings= plsr.x_loadings_
feature_names= X_final.columns.values

# scores plot
plt.figure()
plt.scatter(
    X_scores_anticancer[:, 0],
    X_scores_anticancer[:, 1],
    color='#E23C4A', alpha= 1, label='Noncancer drugs with anti-cancer potential',
    edgecolor='k', s= 30
)
for i, txt in enumerate(anticancer_drugs):
    plt.annotate(
        f"{anticancer_targets[i]}",
        (X_scores_anticancer[i, 0], X_scores_anticancer[i, 1]),
        textcoords="offset points",
        xytext=(5, 10),
        ha="right",
        fontsize=9,
        bbox=dict(boxstyle="round,pad=0.2", alpha=0.3),
    )
plt.scatter(X_scores_bg[:, 0], X_scores_bg[:, 1], color= '#d3d3d3',
            s=15, label='Other noncancer drugs', alpha=1)

plt.title(
    "PLSR Scores Plot", fontsize=14, fontweight="bold"
)
plt.xlabel("PLSR Component 1", fontsize=12)
plt.ylabel("PLSR Component 2", fontsize=12)
plt.legend(fontsize=8)
plt.grid(True, linestyle=":", alpha=0.6)
plt.show()

# loadings plot
# To avoid a messy plot, we plot all targets faintly, but highlight the heavy hitters
loading_magnitudes = np.sqrt(X_loadings[:, 0] ** 2 + X_loadings[:, 1] ** 2)
top_loading_indices = np.argsort(loading_magnitudes)[-10:]  # Top 10 influential targets

# Plot all features background
plt.scatter(X_loadings[:, 0], X_loadings[:, 1],
    color="lightgray",
    alpha=0.5)

# Highlight and label the top influential features
for idx in top_loading_indices:
    plt.scatter(X_loadings[idx, 0], X_loadings[idx, 1],
        color="darkblue", s=50, edgecolors="k")
    clean_label = feature_names[idx].replace("target_", "")
    plt.annotate(clean_label, (X_loadings[idx, 0], X_loadings[idx, 1]),
                textcoords="offset points", xytext=(5, 6),
                ha="right", fontsize=7,fontweight="semibold")

plt.title("PLSR Loadings Plot\n(Target Features)", fontsize=14, fontweight="bold")
plt.xlabel("Loadings on Component 1", fontsize=12)
plt.ylabel("Loadings on Component 2", fontsize=12)
plt.grid(True, linestyle=":", alpha=0.6)
plt.show()

unique_anticancer_targets = np.unique(anticancer_targets)

# Convert target names to match one-hot encoded column names
encoded_anticancer_targets = [f"target_{t}" for t in unique_anticancer_targets]
feature_names_list= list(feature_names)

plt.figure()
plt.scatter(
    X_loadings[:, 0],
    X_loadings[:, 1],
    color="lightgray",
    alpha=0.5,
    label="Other Targets"
)

# highlighting targets of anticancer drugs
for target_col in encoded_anticancer_targets:
    if target_col in feature_names_list:
        # Find the index of this target in the features matrix
        idx = feature_names_list.index(target_col)

        # Plot the highlighted point
        plt.scatter(
            X_loadings[idx, 0],
            X_loadings[idx, 1],
            color="#E23C4A",
            s=30,
            edgecolors="k",
            linewidths=1.5,
            zorder=3,  # Brings points to the front
        )

        # Clean up the name for the text label (remove 'target_' prefix)
        clean_label = target_col.replace("target_", "")

        # Annotate the point
        plt.annotate(
            clean_label,
            (X_loadings[idx, 0], X_loadings[idx, 1]),
            textcoords="offset points",
            xytext=(20, 7), ha="right",
            fontsize=7, fontweight="semibold",
            bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.7, ec="gray"),
        )

plt.title(
    "PLSR Loadings Plot\n(Targets of noncancer drugs\n with anticancer potential)",
    fontsize=14,
    fontweight="bold",
)
plt.xlabel("Loadings on Component 1", fontsize=12)
plt.ylabel("Loadings on Component 2", fontsize=12)
plt.grid(True, linestyle=":", alpha=0.6)

plt.show()